project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Hitting for Six: A Visual Odyssey into the Heart of the Game"
  author:
    - Abhik Biswas (UNI - ab5640)
    - Vedant Goyal (UNI - vg2595 )
  repo-url: https://github.com/The-Code-Commando/EDAV-5702-Final-Project-G40
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cyborg
    code-fold: true


