# Interactive graph

<style>
  * {
    font-family: sans-serif;
  }
  
  .sub-heading {
  font-size: 14px;
  color: #808080
}
  
   .dropdown-btn {
  padding: 4px;
  font-size: 13px;
  cursor: pointer;
  background-color: #fff; 
  color: #080808; 
  border: 1.5px solid #080808;
  transition: background-color 0.3s ease;
}


.dropdown-btn:hover {
  background-color: #080808;
  color:#fff
}


.dropdown-btn.active {
  background-color: #BEBEBE;
  color: #080808;
  border: 1.5px solid #080808;
  
}

  .tooltip {
      position: absolute;
      text-align: center;
      padding: 8px;
      font-size: 12px;
      background: #fff;
      border: 1px solid #ddd;
      border-radius: 5px;
      pointer-events: none; /* Ensure the tooltip does not interfere with mouse events on underlying elements */
      opacity: 0; /* Initially hidden */
    }

</style> 

<h4 id="heading">Batsmen Dismissal Analysis: Percentage Breakdown by Dismissal Type</h4>
<p class="sub-heading"><em>Choose a player from the dropdown menu adjacent to the plot</em></p>

<div id="plot">

</div>

<script src="https://d3js.org/d3.v6.js"></script>
<script type="module" src="scripts/myscript.js"></script>


In the realm of cricket, the analysis of a batsman's dismissals is crucial for opposing teams, providing insights into their strengths and weaknesses. A strategic game plan to dismiss batsmen efficiently contributes significantly to gaining control over a match. Our interactive chart delves into the dismissal types of the world's top 10 run-scorers, offering a visual breakdown to answer the question: "What are the strengths and weaknesses of individual cricketing titans?"

**Before delving into the chart's analysis, it's essential to understand the significance of each dismissal category:**

1. *Bowled:* Occurs when a batsman's wicket is fairly broken by a bowler-delivered ball.
2. *Caught:* Involves a batsman being out when a delivered ball hits the bat and is subsequently held by a fielder without touching the ground.
3. *Caught Behind:* A specific case of being caught out, taken by the wicketkeeper or slip fielders.
4. *Leg Before Wicket (LBW):* Involves a batsman being out if a fair ball hits any part of the body (except the hand) without first touching the bat, with a trajectory indicating it would hit the wickets.
5. *Stumped:* Occurs when a batsman, facing a fair delivery, steps out of the crease, and the wicket is broken by the wicketkeeper, often happening against spin bowlers.
6. *Run Out:* A batsman is declared run out if they fail to get their bat past the crease before it is broken while running between the wickets.
7. *Others:* Encompasses dismissal types like hit-wicket or out due to obstruction.

**Now, understanding the relationship between each dismissal type and a batsman's weaknesses:**

- *Bowled:* Indicates difficulty in covering the line of the ball or flaws in footwork, potentially related to adapting to varying pitch conditions.
- *Caught:* Suggests issues with shot timing or selection, reflecting an aggressive playing style or situational constraints.
- *Caught Behind:* Indicates trouble facing deliveries that seam and swing outward, with vulnerabilities in playing away from the body.
- *LBW:* Suggests challenges in covering the line of the ball and problems facing deliveries that seam and swing inward, possibly coupled with a tendency to play across the line.
- *Stumped:* Indicates a tendency to step out to spinners, exploitable by opposition teams through flighted deliveries.
- *Run Out:* Reflects poor running between the wickets, exploitable by preventing boundaries and encouraging singles and doubles.

Direct inferences from the plots reveal that "Caught Out" is the most common dismissal type, attributed to the aggressive nature of modern cricket. Rare dismissals like hit-wicket or obstruction form a minimal proportion in the game.

**Using the visualization**

The pie chart above provides a visual representation of dismissal types for each batsman, facilitating a detailed comparison. One may select the player from the dropdown menu and hover the mouse on the chart to get the proportion and the actual values of the dismissal.


| Rahul Dravid  | Virat Kohli  |
|---------------|--------------|
| After "Caught Out," the highest proportion is "Bowled," indicating potential issues in covering the line of the ball or foot movement.  | After "Caught Out," the highest proportion is "Caught Behind," revealing difficulties in playing deliveries on the 4th and 5th stump and a tendency to play away from the body. |
| "Run Out" follows, suggesting challenges in running between the wickets. | "Bowled" follows, suggesting challenges against swinging or spinning inward deliveries.  |
| The lowest proportion is "Stumped," indicating Dravid's proficiency against spin. | Notably, Kohli has a considerably lower proportion of "Run Out," indicating his proficiency between the wickets. |

: Comparing the Cricketing Greats *Rahul Dravid* and *Virat Kohli* {.striped .hover}


**Similar insights can be gleaned for other players by selecting them from the dropdown menu.**


