---
execute:
  echo: true
format:
  html:
    fig-width: 11
    fig-height: 7
    out-width: 60%
    embed-resources: true
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r Libraries}

library(ggplot2)
library(plotly)
library(tidyverse)
library(dplyr)
library(parcoords)
library(d3r)
library(GGally)
library(forcats)
library(redav)

```

# Data

```{r}

df <- read.csv("Data_Cricket_Data_by_season_all.csv")

df$Country <- sub(".*\\((.*?)\\).*", "\\1",df$Player)
df$Player <- sub("\\(.*?\\)", paste0(""),df$Player)

df$NotOut <- grepl("\\*", df$HS)

# Convert logical values to "Yes" and "No"
df$NotOut <- ifelse(df$NotOut, "Yes", "No")

df$HS <- gsub("\\*", "", df$HS)

# Assuming df is your dataframe and Season is the column with season values
df$start_year <- (sub("/.*", "", df$Season))  # Extract start year

# For cases like "yyyy/yy" or "yyyy/yy", extract start and end years
if (any(grepl("/", df$Season))) {
  df$start_year <- (sub("/.*", "", df$Season))
  df$end_year <- (paste0(substr(df$Season,1,2),
                                   sub(".*?/(\\d+)$", "\\1", df$Season)))

  } else {
  # For single-value seasons, start and end years are the same
  df$end_year <- df$start_year
}

df$end_year <- gsub("1900", "2000", df$end_year)

df$end_year[df$end_year %in% grep("^.{6}$", df$end_year, value = TRUE)] <- substr(df$end_year[df$end_year %in% grep("^.{6}$", df$end_year, value = TRUE)], 3, 6)

# Convert start_year and end_year to integer

df$Season <- NULL

df <- na.omit(df)

df[df=="-"] <- NA
names(df)[15] <- "start"
names(df)[16] <- "end"
names(df)[5] <- "Runs"


```

## Description

## Missing value analysis

```{r}

library(redav)
####################Plot2######################
plot_missing(df)
####################Plot2######################

```

```{r}

####################### ICC 2011 Final ######################

####### Preprocessing #######
icc_2011 <- read.csv("Data_ICC_2011_F.csv")
icc_2011$match_id <- NULL

icc_2011$wicket_type[icc_2011$wicket_type==""] <- NA
icc_2011$player_dismissed[icc_2011$player_dismissed==""] <- NA
icc_2011$over <- floor(icc_2011$ball)

over_intervals <- cut(icc_2011$over, breaks=seq(0,50,10),
                      include.lowest = TRUE,
                      right = FALSE)
icc_2011$binned_overs <- over_intervals

plot_missing(icc_2011)

```

```{r}

####################### ICC 2015 Final ######################
####### Preprocessing #######
icc_2015 <- read.csv("Data_ICC_2015_F.csv")
icc_2015$match_id <- NULL

icc_2015$wicket_type[icc_2015$wicket_type==""] <- NA
icc_2015$player_dismissed[icc_2015$player_dismissed==""] <- NA
icc_2015$over <- floor(icc_2015$ball)

over_intervals <- cut(icc_2015$over, breaks=seq(0,50,10),
                      include.lowest = TRUE,
                      right = FALSE)
icc_2015$binned_overs <- over_intervals
####### Preprocessing #######


##### Missing Value Plot ####

plot_missing(icc_2015)

```
